require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'keycardiostest' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod "react-native-status-keycard", path: "../node_modules/react-native-status-keycard"
  pod "Keycard", git: "https://github.com/status-im/Keycard.swift.git"
  pod 'secp256k1', git: "https://github.com/status-im/secp256k1.swift.git", submodules: true

  # pod "react-native-status-keycard", path: "../../react-native-status-keycard"
  # pod "Keycard", path: "../../Keycard.swift"
  # pod 'secp256k1.swift', path: "../../secp256k1.swift", :modular_headers => true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |t|
       t.build_configurations.each do |bc|
           bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end
    end
  end
end
